language: python
sudo: required
services:
  - docker

branches:
    only:
        - master
        - /^\d\.\d+$/

matrix:
    include:
        - env: SPLASH_PYTHON_VERSION="3" SPLASH_BUILD_PARALLEL_JOBS=2


before_install:
    - docker build -t splash .
    - docker build -t splash-tests -f dockerfiles/tests/Dockerfile .

script:
    - docker run -it splash-test

#after_success:
#    - codecov
#cache:
#    directories:
#        - $HOME/.cache/pip
